# Generated by Django 4.0.1 on 2022-01-27 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_genome_user_alter_genome_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genome',
            name='user',
        ),
    ]
